import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:megashop/src/blocs/blocs.dart';
import 'package:megashop/src/cubits/cubits.dart';
import 'package:megashop/src/models/models.dart';
import 'package:megashop/src/utilities/utilities.dart';
import 'package:megashop/src/widgets/widgets.dart';
import 'package:velocity_x/velocity_x.dart';

part 'splash_screens.dart';
part 'register_screens.dart';
part 'login_screens.dart';
part 'home_screens.dart';
part 'admin_screens.dart';
part 'detail_product_screens.dart';
part 'profile_screens.dart';
part 'product_screens.dart';
part 'cart_screens.dart';
